# Generated by Django 4.2.7 on 2023-12-05 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_mangement_app', '0003_vendor_average_response_time_vendor_fulfillment_rate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorder',
            name='items',
        ),
    ]
